name: Deploy Vercel

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: build
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Call the web hook
      run: curl -X POST ${{ secrets.VERCEL_WEBHOOK_URL }}
