name: internet yamelo

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    name: build
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Call the web hook
      run: curl -X POST ${{ secrets.API_URL }}
